AWS_LAMBDA_FUNCTION_NAME ?= alertlogic-ciscoduo-collector
AWS_LAMBDA_PACKAGE_NAME ?= al-ciscoduo-collector.zip
AWS_LAMBDA_CONFIG_PATH ?= ./al-ciscoduo-collector.json
AWS_CFN_TEMPLATE_PATH ?= ./cfn/ciscoduo-collector.template

-include ../collector.mk
