AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Run it locally
Resources:
  LocalLambda:
    Type: AWS::Serverless::Function
    Properties:
      KmsKeyArn: <KMS key ARN here>
      Environment:
        Variables:
          AWS_LAMBDA_FUNCTION_NAME:
          aims_secret_key:
          aims_access_key_id:
          al_api:
          stack_name:
          azollect_api:
          ingest_api:
          DEBUG:
          paws_state_queue_arn:
          paws_state_queue_url:
          paws_poll_interval:
          paws_extension:
          okta_endpoint:
          okta_token:
          okta_collection_start_ts:
          collector_id:
      Runtime: nodejs8.10
      Handler: index.handler
      Timeout: 300 
      MemorySize: 1024
