AWS_LAMBDA_FUNCTION_NAME ?= alertlogic-salesforce-collector
AWS_LAMBDA_PACKAGE_NAME ?= al-salesforce-collector.zip
AWS_LAMBDA_CONFIG_PATH ?= ./al-salesforce-collector.json
AWS_CFN_TEMPLATE_PATH ?= ./cfn/salesforce-collector.template

-include ../collector.mk
