AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Run it locally
Resources:
  LocalLambda:
    Type: AWS::Serverless::Function
    Properties:
      KmsKeyArn: arn:aws:kms:us-east-1:352283894008:key/c31cd559-a589-417b-91bb-19bfbcba903f
      Environment:
        Variables:
          AWS_LAMBDA_FUNCTION_NAME:
          aims_secret_key:
          aims_access_key_id:
          al_api:
          stack_name:
          azcollect_api:
          ingest_api:
          DEBUG:
          paws_state_queue_arn:
          paws_state_queue_url:
          paws_poll_interval:
          paws_extension:
          paws_secret_param_name:
          paws_endpoint:
          paws_api_client_id:
          paws_max_pages_per_invocation:
          paws_collector_param_string_1:
          paws_collector_param_string_2:
          collector_streams:
          collector_id:
          paws_ddb_table_name:
          customer_id:
          ssm_direct:
          paws_type_name:
      CodeUri: /Users/imransyed/Downloads/projects/alertlogic-collectors/paws-collector/collectors/mimecast
      Runtime: nodejs14.x
      Handler: index.handler
      Timeout: 300 
      MemorySize: 1024
