AWS_LAMBDA_FUNCTION_NAME ?= alertlogic-sophossiem-collector
AWS_LAMBDA_PACKAGE_NAME ?= al-sophossiem-collector.zip
AWS_LAMBDA_CONFIG_PATH ?= ./al-sophossiem-collector.json
AWS_CFN_TEMPLATE_PATH ?= ./cfn/sophossiem-collector.template

-include ../collector.mk
