AWS_LAMBDA_FUNCTION_NAME ?= alertlogic-googlestackdriver-collector
AWS_LAMBDA_PACKAGE_NAME ?= al-googlestackdriver-collector.zip
AWS_LAMBDA_S3_BUCKET ?= alertlogic-collectors

-include ../collector.mk
