AWS_LAMBDA_FUNCTION_NAME ?= alertlogic-googlestackdriver-collector
AWS_LAMBDA_PACKAGE_NAME ?= al-googlestackdriver-collector.zip
AWS_LAMBDA_CONFIG_PATH ?= ./al-googlestackdriver-collector.json
AWS_CFN_TEMPLATE_PATH ?= ./cfn/googlestackdriver-collector.template

-include ../collector.mk
