AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Run it locally
Resources:
  LocalLambda:
    Type: AWS::Serverless::Function
    Properties:
      KmsKeyArn: your-arn-here
      Environment:
        Variables:
          AWS_LAMBDA_FUNCTION_NAME:
          aims_secret_key:
          aims_access_key_id:
          al_api:
          al_application_id:
          stack_name:
          azollect_api:
          ingest_api:
          DEBUG:
          paws_state_queue_arn:
          paws_state_queue_url:
          paws_poll_interval:
          paws_extension:
          paws_secret_param_name:
          paws_api_secret:
          paws_api_client_id:  
          paws_endpoint: 
          paws_collector_param_string_1:
          paws_collector_param_string_2:
          paws_max_pages_per_invocation:          
          collector_id:
      Runtime: nodejs10.x
      Handler: index.handler
      Timeout: 300 
      MemorySize: 1024
