AWS_LAMBDA_FUNCTION_NAME ?= alertlogic-crowdstrike-collector
AWS_LAMBDA_PACKAGE_NAME ?= al-crowdstrike-collector.zip
AWS_LAMBDA_CONFIG_PATH ?= ./al-crowdstrike-collector.json
AWS_CFN_TEMPLATE_PATH ?= ./cfn/crowdstrike-collector.template

-include ../collector.mk
