AWS_LAMBDA_FUNCTION_NAME ?= alertlogic-sophos-collector
AWS_LAMBDA_PACKAGE_NAME ?= al-sophos-collector.zip
AWS_LAMBDA_CONFIG_PATH ?= ./al-sophos-collector.json
AWS_CFN_TEMPLATE_PATH ?= ./cfn/sophos-collector.template

-include ../collector.mk
