AWS_LAMBDA_FUNCTION_NAME ?= alertlogic-mimecast-collector
AWS_LAMBDA_PACKAGE_NAME ?= al-mimecast-collector.zip
AWS_LAMBDA_CONFIG_PATH ?= ./al-mimecast-collector.json
AWS_CFN_TEMPLATE_PATH ?= ./cfn/mimecast-collector.template

-include ../collector.mk
