AWS_LAMBDA_FUNCTION_NAME ?= alertlogic-{{type}}-collector
AWS_LAMBDA_PACKAGE_NAME ?= al-{{type}}-collector.zip
AWS_LAMBDA_CONFIG_PATH ?= ./al-{{type}}-collector.json
AWS_CFN_TEMPLATE_PATH ?= ./cfn/{{type}}-collector.template

-include ../collector.mk
