AWS_LAMBDA_FUNCTION_NAME ?= alertlogic-gsuite-collector
AWS_LAMBDA_PACKAGE_NAME ?= al-gsuite-collector.zip
AWS_LAMBDA_CONFIG_PATH ?= ./al-gsuite-collector.json
AWS_CFN_TEMPLATE_PATH ?= ./cfn/gsuite_collector.template

-include ../collector.mk
