AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Run it locally
Resources:
  LocalLambda:
    Type: AWS::Serverless::Function
    Properties:
      KmsKeyArn: your-arn-here
      Environment:
        Variables:
          AWS_LAMBDA_FUNCTION_NAME:
          aims_secret_key:
          aims_access_key_id:
          al_api:
          stack_name:
          azcollect_api:
          ingest_api:
          DEBUG:
          paws_state_queue_arn:
          paws_state_queue_url:
          paws_poll_interval:
          paws_extension:
          paws_secret_param_name:
          paws_endpoint:
          paws_api_client_id:
          paws_max_pages_per_invocation:    
          collector_id:
          paws_ddb_table_name:
          collector_streams:
      Runtime: nodejs10.x
      Handler: index.handler
      Timeout: 300 
      MemorySize: 1024
