AWS_LAMBDA_FUNCTION_NAME ?= alertlogic-ciscomeraki-collector
AWS_LAMBDA_PACKAGE_NAME ?= al-ciscomeraki-collector.zip
AWS_LAMBDA_CONFIG_PATH ?= ./al-ciscomeraki-collector.json
AWS_CFN_TEMPLATE_PATH ?= ./cfn/ciscomeraki-collector.template

-include ../collector.mk
