AWS_LAMBDA_FUNCTION_NAME ?= alertlogic-carbonblack-collector
AWS_LAMBDA_PACKAGE_NAME ?= al-carbonblack-collector.zip
AWS_LAMBDA_CONFIG_PATH ?= ./al-carbonblack-collector.json
AWS_CFN_TEMPLATE_PATH ?= ./cfn/carbonblack-collector.template

-include ../collector.mk
