AWS_LAMBDA_FUNCTION_NAME ?= alertlogic-sentinelone-collector
AWS_LAMBDA_PACKAGE_NAME ?= al-sentinelone-collector.zip
AWS_LAMBDA_CONFIG_PATH ?= ./al-sentinelone-collector.json
AWS_CFN_TEMPLATE_PATH ?= ./cfn/sentinelone-collector.template

-include ../collector.mk
