AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Run it locally
Resources:
  LocalLambda:
    Type: AWS::Serverless::Function
    Properties:
      KmsKeyArn: 
      Environment:
        Variables:
          AWS_LAMBDA_FUNCTION_NAME:
          aims_secret_key:
          aims_access_key_id:
          al_api:
          stack_name:
          azcollect_api:
          collector_status_api:
          ingest_api:
          DEBUG:
          paws_state_queue_arn:
          paws_state_queue_url:
          paws_poll_interval:
          paws_secret_param_name:
          paws_api_client_id:
          paws_max_pages_per_invocation:
          paws_collector_param_string_2:
          paws_collector_param_string_1:
          paws_endpoint:
          paws_extension:
          collector_id:
          paws_ddb_table_name:
          collector_streams:
          customer_id:
          paws_type_name:
          ssm_direct:
          collector_status_api: api.product.dev.alertlogic.com
      CodeUri: 
      Runtime: nodejs22.x
      Handler: index.handler
      Timeout: 600
      MemorySize: 1024
