AWS_LAMBDA_FUNCTION_NAME ?= alertlogic-ciscoamp-collector
AWS_LAMBDA_PACKAGE_NAME ?= al-ciscoamp-collector.zip
AWS_LAMBDA_CONFIG_PATH ?= ./al-ciscoamp-collector.json
AWS_CFN_TEMPLATE_PATH ?= ./cfn/ciscoamp-collector.template

-include ../collector.mk
