on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: make test-all
      run: |
        make test-all

    - name: Test and Generate Coverage
      uses: 5monkeys/cobertura-action@master
      with:
       path: ./coverage/*.xml
       repo_token: ${{secrets.GITHUB_TOKEN}}
       minimum_coverage: 75