AWS_LAMBDA_FUNCTION_NAME ?= alertlogic-auth0-collector
AWS_LAMBDA_PACKAGE_NAME ?= al-auth0-collector.zip
AWS_LAMBDA_CONFIG_PATH ?= ./al-auth0-collector.json
AWS_CFN_TEMPLATE_PATH ?= ./cfn/auth0-collector.template

-include ../collector.mk
