version: 1.0
service_name: paws/auth0

stages:
  - name: test_manual
    image: 422372788747.dkr.ecr.us-east-1.amazonaws.com/al-paws-collector-pipeline:latest
    compute_size: small_arm
    when:
      - pull_request:
        trigger_phrase: build-collector-auth0
    commands:
      - source $NVM_DIR/nvm.sh && nvm use 18
      - export ALPS_SERVICE_VERSION=$(node -p "require('./package.json').version")
      # - echo "ALPS_SERVICE_VERSION=$ALPS_SERVICE_VERSION" >> $GITHUB_ENV
      - npm install
      - make package
      - mkdir auth0-collecctor
      - cp -r cfn al-auth0-collector.zip al-auth0-collector.json auth0-collector
    env:
      - ALPS_SERVICE_VERSION: ${{ env.ALPS_SERVICE_VERSION }}
    outputs:
      file: ./auth0-collecctor
    packagers:
      - basic
