AWS_LAMBDA_FUNCTION_NAME ?= alertlogic-okta-collector
AWS_LAMBDA_PACKAGE_NAME ?= al-okta-collector.zip
AWS_LAMBDA_CONFIG_PATH ?= ./al-okta-collector.json
AWS_CFN_TEMPLATE_PATH ?= ./cfn/okta-collector.template

-include ../collector.mk
